--- # splunk on a aws server

- hosts: all
  become: yes
  remote_user: ec2-user
  tasks:
    - name: Download Splunk
      get_url: 
        url: https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=8.0.1&product=splunk&filename=splunk-8.0.1-6db836e2fb9e-Linux-x86_64.tgz&wget=true
        dest: /opt/splunk.tgz
        force_basic_auth: yes
    - name: Extract Splunk Binary
      command: chdir=/opt tar -xzvf splunk.tgz 
    - name: Start splunk
      command: /opt/splunk/bin/splunk start --accept-license --answer-yes
    - name: Enable Splunk Boot Start
      command: /opt/splunk/bin/splunk enable boot-start